name: PlayerPasswords
version: 1.0
author: FireWolf
main: firewolf8385.playerpasswords.PlayerPasswords
commands:
  login:
    usage: /<command>
    description: Allows the player to login.
  register:
    usage: /<command>
    description: Allows the player to set their password.
  playerpasswords:
    usage: /<command>
    description: Main plugin command.
    aliases: [playerpassword, pp]
  password:
    usage: /<command>
    description: Player password settings